/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Calci;

/**
 *
 * @author Kunwar
 */
public class Model extends javax.swing.JFrame
{

    /**
     * Creates new form Model
     */
    public Model()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton21 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 40, 420, 50);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 420, 30);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 110, 60, 40);

        jButton2.setText("jButton1");
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 110, 60, 40);

        jButton3.setText("jButton1");
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 110, 60, 40);

        jButton4.setText("jButton1");
        getContentPane().add(jButton4);
        jButton4.setBounds(250, 110, 60, 40);

        jButton5.setText("jButton1");
        getContentPane().add(jButton5);
        jButton5.setBounds(190, 150, 60, 40);

        jButton6.setText("jButton1");
        getContentPane().add(jButton6);
        jButton6.setBounds(130, 150, 60, 40);

        jButton7.setText("jButton1");
        getContentPane().add(jButton7);
        jButton7.setBounds(250, 150, 60, 40);

        jButton8.setText("jButton1");
        getContentPane().add(jButton8);
        jButton8.setBounds(370, 150, 60, 40);

        jButton9.setText("jButton1");
        getContentPane().add(jButton9);
        jButton9.setBounds(190, 230, 60, 40);

        jButton10.setText("jButton1");
        getContentPane().add(jButton10);
        jButton10.setBounds(190, 190, 60, 40);

        jButton11.setText("jButton1");
        getContentPane().add(jButton11);
        jButton11.setBounds(250, 190, 60, 40);

        jButton12.setText("jButton1");
        getContentPane().add(jButton12);
        jButton12.setBounds(250, 230, 60, 40);

        jButton13.setText("jButton1");
        getContentPane().add(jButton13);
        jButton13.setBounds(370, 270, 60, 40);

        jButton14.setText("jButton1");
        getContentPane().add(jButton14);
        jButton14.setBounds(310, 150, 60, 40);

        jButton15.setText("jButton1");
        getContentPane().add(jButton15);
        jButton15.setBounds(370, 190, 60, 40);

        jButton16.setText("jButton1");
        getContentPane().add(jButton16);
        jButton16.setBounds(370, 230, 60, 40);

        jButton17.setText("jButton1");
        getContentPane().add(jButton17);
        jButton17.setBounds(310, 190, 60, 40);

        jButton18.setText("jButton1");
        getContentPane().add(jButton18);
        jButton18.setBounds(310, 270, 60, 40);

        jButton19.setText("jButton1");
        getContentPane().add(jButton19);
        jButton19.setBounds(190, 270, 60, 40);

        jButton20.setText("jButton1");
        getContentPane().add(jButton20);
        jButton20.setBounds(250, 270, 60, 40);

        jButton22.setText("jButton1");
        getContentPane().add(jButton22);
        jButton22.setBounds(10, 150, 60, 40);

        jButton23.setText("jButton1");
        getContentPane().add(jButton23);
        jButton23.setBounds(10, 190, 60, 40);

        jButton24.setText("jButton1");
        getContentPane().add(jButton24);
        jButton24.setBounds(10, 230, 60, 40);

        jButton25.setText("jButton1");
        getContentPane().add(jButton25);
        jButton25.setBounds(10, 270, 60, 40);

        jButton26.setText("jButton1");
        getContentPane().add(jButton26);
        jButton26.setBounds(70, 270, 60, 40);

        jButton27.setText("jButton1");
        getContentPane().add(jButton27);
        jButton27.setBounds(70, 230, 60, 40);

        jButton28.setText("jButton1");
        getContentPane().add(jButton28);
        jButton28.setBounds(70, 190, 60, 40);

        jButton29.setText("jButton1");
        getContentPane().add(jButton29);
        jButton29.setBounds(70, 110, 60, 40);

        jButton31.setText("jButton1");
        getContentPane().add(jButton31);
        jButton31.setBounds(130, 110, 60, 40);

        jButton32.setText("jButton1");
        getContentPane().add(jButton32);
        jButton32.setBounds(70, 150, 60, 40);

        jButton33.setText("jButton1");
        getContentPane().add(jButton33);
        jButton33.setBounds(130, 190, 60, 40);

        jButton34.setText("jButton1");
        getContentPane().add(jButton34);
        jButton34.setBounds(130, 230, 60, 40);

        jButton35.setText("jButton1");
        getContentPane().add(jButton35);
        jButton35.setBounds(130, 270, 60, 40);

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(10, 110, 60, 40);

        jButton21.setText("jButton1");
        getContentPane().add(jButton21);
        jButton21.setBounds(310, 230, 60, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Model().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
