/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Learn;

/**
 *
 * @author Kunwar
 */
public class puzzle extends javax.swing.JFrame
{

    /**
     * Creates new form puzzle
     */
    public puzzle()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jB4 = new javax.swing.JButton();
        jB15 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB10 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        jB14 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB1 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jB4.setText("4");
        getContentPane().add(jB4);
        jB4.setBounds(70, 30, 60, 50);

        jB15.setText("15");
        getContentPane().add(jB15);
        jB15.setBounds(130, 30, 60, 50);

        jB7.setText("7");
        getContentPane().add(jB7);
        jB7.setBounds(190, 30, 60, 50);

        jB8.setText("8");
        getContentPane().add(jB8);
        jB8.setBounds(10, 80, 60, 50);

        jB10.setText("10");
        getContentPane().add(jB10);
        jB10.setBounds(70, 80, 60, 50);

        jB2.setText("2");
        getContentPane().add(jB2);
        jB2.setBounds(130, 80, 60, 50);

        jB11.setText("11");
        getContentPane().add(jB11);
        jB11.setBounds(190, 80, 60, 50);

        jB14.setText("14");
        getContentPane().add(jB14);
        jB14.setBounds(10, 130, 60, 50);

        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jB3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB3);
        jB3.setBounds(70, 130, 60, 50);

        jB13.setText("13");
        getContentPane().add(jB13);
        jB13.setBounds(190, 130, 60, 50);

        jB1.setText("1");
        getContentPane().add(jB1);
        jB1.setBounds(10, 30, 60, 50);

        jB12.setText("12");
        getContentPane().add(jB12);
        jB12.setBounds(10, 180, 60, 50);

        jB9.setText("9");
        getContentPane().add(jB9);
        jB9.setBounds(70, 180, 60, 50);

        jB5.setText("5");
        getContentPane().add(jB5);
        jB5.setBounds(130, 180, 60, 50);
        getContentPane().add(jB);
        jB.setBounds(190, 180, 60, 50);

        jB6.setText("6");
        getContentPane().add(jB6);
        jB6.setBounds(130, 130, 60, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jB3ActionPerformed
    {//GEN-HEADEREND:event_jB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new puzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB10;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB14;
    private javax.swing.JButton jB15;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    // End of variables declaration//GEN-END:variables
}
