/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Sudo;

/**
 *
 * @author Kunwar
 */
public class Model extends javax.swing.JFrame
{

    /**
     * Creates new form Model
     */
    public Model()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jTextField46 = new javax.swing.JTextField();
        jTextField47 = new javax.swing.JTextField();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jTextField50 = new javax.swing.JTextField();
        jTextField51 = new javax.swing.JTextField();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        jTextField54 = new javax.swing.JTextField();
        jTextField55 = new javax.swing.JTextField();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jTextField58 = new javax.swing.JTextField();
        jTextField59 = new javax.swing.JTextField();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextField62 = new javax.swing.JTextField();
        jTextField63 = new javax.swing.JTextField();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jTextField66 = new javax.swing.JTextField();
        jTextField67 = new javax.swing.JTextField();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jTextField70 = new javax.swing.JTextField();
        jTextField71 = new javax.swing.JTextField();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jTextField74 = new javax.swing.JTextField();
        jTextField75 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jTextField78 = new javax.swing.JTextField();
        jTextField79 = new javax.swing.JTextField();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField82 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(290, 30, 30, 30);

        jTextField2.setText("1");
        jTextField2.setAlignmentX(3.0F);
        jTextField2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(50, 30, 30, 30);

        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(80, 30, 30, 30);

        jTextField4.setText("jTextField1");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(110, 30, 30, 30);

        jTextField5.setText("jTextField1");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(140, 30, 30, 30);

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(170, 30, 30, 30);

        jTextField7.setText("jTextField1");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(200, 30, 30, 30);

        jTextField8.setText("jTextField1");
        getContentPane().add(jTextField8);
        jTextField8.setBounds(230, 30, 30, 30);

        jTextField9.setText("jTextField1");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(260, 30, 30, 30);

        jTextField10.setText("jTextField1");
        getContentPane().add(jTextField10);
        jTextField10.setBounds(50, 60, 30, 30);

        jTextField11.setText("jTextField1");
        getContentPane().add(jTextField11);
        jTextField11.setBounds(80, 60, 30, 30);

        jTextField12.setText("jTextField1");
        getContentPane().add(jTextField12);
        jTextField12.setBounds(110, 60, 30, 30);

        jTextField13.setText("jTextField1");
        getContentPane().add(jTextField13);
        jTextField13.setBounds(140, 60, 30, 30);

        jTextField14.setText("jTextField1");
        getContentPane().add(jTextField14);
        jTextField14.setBounds(170, 60, 30, 30);

        jTextField15.setText("jTextField1");
        getContentPane().add(jTextField15);
        jTextField15.setBounds(200, 60, 30, 30);

        jTextField16.setText("jTextField1");
        getContentPane().add(jTextField16);
        jTextField16.setBounds(230, 60, 30, 30);

        jTextField17.setText("jTextField1");
        getContentPane().add(jTextField17);
        jTextField17.setBounds(260, 60, 30, 30);

        jTextField18.setText("jTextField1");
        getContentPane().add(jTextField18);
        jTextField18.setBounds(290, 60, 30, 30);

        jTextField19.setText("jTextField1");
        getContentPane().add(jTextField19);
        jTextField19.setBounds(50, 90, 30, 30);

        jTextField20.setText("jTextField1");
        getContentPane().add(jTextField20);
        jTextField20.setBounds(80, 90, 30, 30);

        jTextField21.setText("jTextField1");
        getContentPane().add(jTextField21);
        jTextField21.setBounds(110, 90, 30, 30);

        jTextField22.setText("jTextField1");
        getContentPane().add(jTextField22);
        jTextField22.setBounds(140, 90, 30, 30);

        jTextField23.setText("jTextField1");
        getContentPane().add(jTextField23);
        jTextField23.setBounds(170, 90, 30, 30);

        jTextField24.setText("jTextField1");
        getContentPane().add(jTextField24);
        jTextField24.setBounds(200, 90, 30, 30);

        jTextField25.setText("jTextField1");
        getContentPane().add(jTextField25);
        jTextField25.setBounds(260, 90, 30, 30);

        jTextField26.setText("jTextField1");
        getContentPane().add(jTextField26);
        jTextField26.setBounds(230, 90, 30, 30);

        jTextField27.setText("jTextField1");
        getContentPane().add(jTextField27);
        jTextField27.setBounds(290, 90, 30, 30);

        jTextField28.setText("jTextField1");
        getContentPane().add(jTextField28);
        jTextField28.setBounds(50, 120, 30, 30);

        jTextField29.setText("jTextField1");
        getContentPane().add(jTextField29);
        jTextField29.setBounds(50, 150, 30, 30);

        jTextField30.setText("jTextField1");
        getContentPane().add(jTextField30);
        jTextField30.setBounds(50, 180, 30, 30);

        jTextField31.setText("jTextField1");
        getContentPane().add(jTextField31);
        jTextField31.setBounds(80, 180, 30, 30);

        jTextField32.setText("jTextField1");
        getContentPane().add(jTextField32);
        jTextField32.setBounds(80, 150, 30, 30);

        jTextField33.setText("jTextField1");
        getContentPane().add(jTextField33);
        jTextField33.setBounds(80, 120, 30, 30);

        jTextField34.setText("jTextField1");
        getContentPane().add(jTextField34);
        jTextField34.setBounds(110, 120, 30, 30);

        jTextField35.setText("jTextField1");
        getContentPane().add(jTextField35);
        jTextField35.setBounds(110, 150, 30, 30);

        jTextField36.setText("jTextField1");
        getContentPane().add(jTextField36);
        jTextField36.setBounds(110, 180, 30, 30);

        jTextField37.setText("jTextField1");
        getContentPane().add(jTextField37);
        jTextField37.setBounds(140, 180, 30, 30);

        jTextField38.setText("jTextField1");
        getContentPane().add(jTextField38);
        jTextField38.setBounds(140, 150, 30, 30);

        jTextField39.setText("jTextField1");
        getContentPane().add(jTextField39);
        jTextField39.setBounds(140, 120, 30, 30);

        jTextField40.setText("jTextField1");
        getContentPane().add(jTextField40);
        jTextField40.setBounds(170, 120, 30, 30);

        jTextField41.setText("jTextField1");
        getContentPane().add(jTextField41);
        jTextField41.setBounds(170, 180, 30, 30);

        jTextField42.setText("jTextField1");
        getContentPane().add(jTextField42);
        jTextField42.setBounds(170, 150, 30, 30);

        jTextField43.setText("jTextField1");
        getContentPane().add(jTextField43);
        jTextField43.setBounds(200, 150, 30, 30);

        jTextField44.setText("jTextField1");
        getContentPane().add(jTextField44);
        jTextField44.setBounds(200, 120, 30, 30);

        jTextField45.setText("jTextField1");
        getContentPane().add(jTextField45);
        jTextField45.setBounds(200, 180, 30, 30);

        jTextField46.setText("jTextField1");
        getContentPane().add(jTextField46);
        jTextField46.setBounds(230, 180, 30, 30);

        jTextField47.setText("jTextField1");
        getContentPane().add(jTextField47);
        jTextField47.setBounds(230, 150, 30, 30);

        jTextField48.setText("jTextField1");
        getContentPane().add(jTextField48);
        jTextField48.setBounds(230, 120, 30, 30);

        jTextField49.setText("jTextField1");
        getContentPane().add(jTextField49);
        jTextField49.setBounds(260, 120, 30, 30);

        jTextField50.setText("jTextField1");
        getContentPane().add(jTextField50);
        jTextField50.setBounds(260, 150, 30, 30);

        jTextField51.setText("jTextField1");
        getContentPane().add(jTextField51);
        jTextField51.setBounds(260, 180, 30, 30);

        jTextField52.setText("jTextField1");
        getContentPane().add(jTextField52);
        jTextField52.setBounds(290, 180, 30, 30);

        jTextField53.setText("jTextField1");
        getContentPane().add(jTextField53);
        jTextField53.setBounds(290, 150, 30, 30);

        jTextField54.setText("jTextField1");
        getContentPane().add(jTextField54);
        jTextField54.setBounds(290, 120, 30, 30);

        jTextField55.setText("jTextField1");
        getContentPane().add(jTextField55);
        jTextField55.setBounds(50, 240, 30, 30);

        jTextField56.setText("jTextField1");
        getContentPane().add(jTextField56);
        jTextField56.setBounds(170, 240, 30, 30);

        jTextField57.setText("jTextField1");
        getContentPane().add(jTextField57);
        jTextField57.setBounds(80, 240, 30, 30);

        jTextField58.setText("jTextField1");
        getContentPane().add(jTextField58);
        jTextField58.setBounds(110, 210, 30, 30);

        jTextField59.setText("jTextField1");
        getContentPane().add(jTextField59);
        jTextField59.setBounds(50, 270, 30, 30);

        jTextField60.setText("jTextField1");
        getContentPane().add(jTextField60);
        jTextField60.setBounds(110, 240, 30, 30);

        jTextField61.setText("jTextField1");
        getContentPane().add(jTextField61);
        jTextField61.setBounds(260, 270, 30, 30);

        jTextField62.setText("jTextField1");
        getContentPane().add(jTextField62);
        jTextField62.setBounds(230, 270, 30, 30);

        jTextField63.setText("jTextField1");
        getContentPane().add(jTextField63);
        jTextField63.setBounds(260, 240, 30, 30);

        jTextField64.setText("jTextField1");
        getContentPane().add(jTextField64);
        jTextField64.setBounds(230, 210, 30, 30);

        jTextField65.setText("jTextField1");
        getContentPane().add(jTextField65);
        jTextField65.setBounds(110, 270, 30, 30);

        jTextField66.setText("jTextField1");
        getContentPane().add(jTextField66);
        jTextField66.setBounds(290, 270, 30, 30);

        jTextField67.setText("jTextField1");
        getContentPane().add(jTextField67);
        jTextField67.setBounds(140, 240, 30, 30);

        jTextField68.setText("jTextField1");
        getContentPane().add(jTextField68);
        jTextField68.setBounds(290, 210, 30, 30);

        jTextField69.setText("jTextField1");
        getContentPane().add(jTextField69);
        jTextField69.setBounds(80, 270, 30, 30);

        jTextField70.setText("jTextField1");
        getContentPane().add(jTextField70);
        jTextField70.setBounds(200, 270, 30, 30);

        jTextField71.setText("jTextField1");
        getContentPane().add(jTextField71);
        jTextField71.setBounds(260, 210, 30, 30);

        jTextField72.setText("jTextField1");
        getContentPane().add(jTextField72);
        jTextField72.setBounds(80, 210, 30, 30);

        jTextField73.setText("jTextField1");
        getContentPane().add(jTextField73);
        jTextField73.setBounds(140, 270, 30, 30);

        jTextField74.setText("jTextField1");
        getContentPane().add(jTextField74);
        jTextField74.setBounds(200, 210, 30, 30);

        jTextField75.setText("jTextField1");
        getContentPane().add(jTextField75);
        jTextField75.setBounds(170, 270, 30, 30);

        jTextField76.setText("jTextField1");
        getContentPane().add(jTextField76);
        jTextField76.setBounds(170, 210, 30, 30);

        jTextField77.setText("jTextField1");
        getContentPane().add(jTextField77);
        jTextField77.setBounds(290, 240, 30, 30);

        jTextField78.setText("jTextField1");
        getContentPane().add(jTextField78);
        jTextField78.setBounds(140, 210, 30, 30);

        jTextField79.setText("jTextField1");
        getContentPane().add(jTextField79);
        jTextField79.setBounds(230, 240, 30, 30);

        jTextField80.setText("jTextField1");
        getContentPane().add(jTextField80);
        jTextField80.setBounds(200, 240, 30, 30);

        jTextField81.setText("jTextField1");
        getContentPane().add(jTextField81);
        jTextField81.setBounds(50, 210, 30, 30);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 170, 130, 40);

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 110, 130, 40);

        jTextField82.setText("Timer Starts with click of the start Button and stops with submit");
        getContentPane().add(jTextField82);
        jTextField82.setBounds(350, 10, 240, 30);

        jButton3.setText("New Game");
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 230, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
    {//GEN-HEADEREND:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Model.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Model().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField46;
    private javax.swing.JTextField jTextField47;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField50;
    private javax.swing.JTextField jTextField51;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField54;
    private javax.swing.JTextField jTextField55;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField58;
    private javax.swing.JTextField jTextField59;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField62;
    private javax.swing.JTextField jTextField63;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField66;
    private javax.swing.JTextField jTextField67;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField70;
    private javax.swing.JTextField jTextField71;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField74;
    private javax.swing.JTextField jTextField75;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField78;
    private javax.swing.JTextField jTextField79;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField82;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
