/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.naming.spi.DirStateFactory.Result;
import javax.swing.JOptionPane;

/**
 *
 * @author Kunwar
 */
public class LoginFrame extends javax.swing.JFrame
{

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        UN = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        UNF = new javax.swing.JTextField();
        PF = new javax.swing.JPasswordField();
        RB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(471, 226));
        setResizable(false);
        getContentPane().setLayout(null);

        UN.setText("User Name");
        getContentPane().add(UN);
        UN.setBounds(130, 60, 70, 30);

        P.setText("Password");
        getContentPane().add(P);
        P.setBounds(130, 110, 60, 20);
        getContentPane().add(UNF);
        UNF.setBounds(200, 60, 130, 30);

        PF.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PFActionPerformed(evt);
            }
        });
        getContentPane().add(PF);
        PF.setBounds(200, 100, 130, 30);

        RB.setText("Reset");
        getContentPane().add(RB);
        RB.setBounds(120, 160, 90, 23);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 160, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PFActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PFActionPerformed
    {//GEN-HEADEREND:event_PFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PFActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        String UN = UNF.getText();
        String PW = String.valueOf(PF.getPassword());
        Connection conn = null;
        PreparedStatement pstmt = null;
        Result set = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///user","root","");
            pstmt = conn.prepareStatement("select * from userdetail where userdetail = ?");
            pstmt.setString(1, UN);
            ResultSet rs;
            rs=pstmt.executeQuery();
            while(rs.next())
            {
                if(PW.equals(rs.getString("passwrd")))
                    JOptionPane.showMessageDialog(null, "Login Succesfull");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P;
    private javax.swing.JPasswordField PF;
    private javax.swing.JButton RB;
    private javax.swing.JLabel UN;
    private javax.swing.JTextField UNF;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
