/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Kunwar
 */
public class SignupForm extends javax.swing.JFrame
{

    /**
     * Creates new form SignupForm
     */
    public SignupForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLusernam = new javax.swing.JLabel();
        jlPswd = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();
        JTUn = new javax.swing.JTextField();
        JtId = new javax.swing.JTextField();
        JPswd = new javax.swing.JPasswordField();
        JbSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jLusernam.setText("User Name");
        getContentPane().add(jLusernam);
        jLusernam.setBounds(90, 40, 70, 30);

        jlPswd.setText("Password");
        getContentPane().add(jlPswd);
        jlPswd.setBounds(90, 90, 70, 30);

        jlId.setText("Identity");
        getContentPane().add(jlId);
        jlId.setBounds(90, 140, 70, 30);
        getContentPane().add(JTUn);
        JTUn.setBounds(170, 40, 110, 30);
        getContentPane().add(JtId);
        JtId.setBounds(170, 140, 110, 30);
        getContentPane().add(JPswd);
        JPswd.setBounds(170, 90, 110, 30);

        JbSubmit.setText("Submit");
        JbSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JbSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(JbSubmit);
        JbSubmit.setBounds(140, 200, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbSubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JbSubmitActionPerformed
    {//GEN-HEADEREND:event_JbSubmitActionPerformed
       String Un = JTUn.getText();
       String Id = JtId.getText();
       String Pw = String.valueOf(JPswd.getPassword());
        Connection conn = null;
        PreparedStatement pstmt = null;
        try{
            Class.forName("com.mysql.jdhc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql:///user","root","");
            pstmt=conn.prepareStatement("insert into userdetail values (? ? ?)");
            pstmt.setString(1, Un);
            pstmt.setString(2, Pw);
            pstmt.setString(3, Id);
            int i = pstmt.executeUpdate();
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Data is Saved");
            }
            else
                JOptionPane.showMessageDialog(null, "data is not saved");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_JbSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPswd;
    private javax.swing.JTextField JTUn;
    private javax.swing.JButton JbSubmit;
    private javax.swing.JTextField JtId;
    private javax.swing.JLabel jLusernam;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlPswd;
    // End of variables declaration//GEN-END:variables
}
